/**
 * This module is only available to [service workers](https://kit.svelte.dev/docs/service-workers).
 */
declare module "$service-worker" {
  /**
   * The `base` path of the deployment. Typically this is equivalent to `config.kit.paths.base`, but it is calculated from `location.pathname` meaning that it will continue to work correctly if the site is deployed to a subdirectory.
   * Note that there is a `base` but no `assets`, since service workers cannot be used if `config.kit.paths.assets` is specified.
   */
  export const base: string;

  /**
   * An array of URL strings representing the files generated by Vite, suitable for caching with `cache.addAll(build)`.
   * During development, this is an empty array.
   */
  export const build: string[];

  /**
   * An array of URL strings representing the files in your static directory, or whatever directory is specified by `config.kit.files.assets`. You can customize which files are included from `static` directory using [`config.kit.serviceWorker.files`](https://kit.svelte.dev/docs/configuration)
   */
  export const files: string[];
}
